### ISSUE TITLE
Images in the documentation

### ISSUE THREAD

**Issue by Janiczek** [alexandrepiveteau/elm-algebraic-graph#1]
Hello!
I don't know if it's the wording or what, but I felt a bit confused by the description of `union` and `product` - it wasn't really clear to me whether `union` adds edges or not, etc.
The original paper has some nice figures that help the intuition (or at least helped me):
![operations](https://user-images.githubusercontent.com/149425/61773998-43a5a500-adf6-11e9-9281-4daed70a45b6.png)
Maybe you can add them to the README or the actual docs? (I'm not sure of the licensing...)

**Comment by alexandrepiveteau** [comment]
Hi !
Thanks for the suggestion. I do plan to improve the documentation a bit in the coming weeks (or maybe next month, I have some college exams soon), especially by adding some code examples for the different library functions that show their effects better.

The point you raise is interesting – do you think that using `union` and `product` is not appropriate in this context, and that the library should switch to the original paper terminology with `overlay` and `connect` ? I originally thought that `union` would be consistent with Elm core's `Set.union`, and that `product` would remind the user of Cartesian products.

This is definitely a question that requires an answer before the next major release though, so we can integrate an breaking change to use better naming conventions. Thanks for pointing that out !

**Comment by Janiczek** [comment]
No, I don't suggest changing the names, even though `overlay` gives a little bit more intuition about not adding any edges. I think `union` and `product` are mostly fine, just that the documentation could say / show that it doesn't add / does add edges, and how.
